### ISSUE TITLE
Public API for Terraform CLI / TF Cloud exec code

### ISSUE THREAD

**Issue by ansgarm** [hashicorp/terraform-cdk#804]
### Community Note

- Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
- Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
- If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
[Internally](https://github.com/hashicorp/terraform-cdk/tree/v0.4.1/packages/cdktf-cli/bin/cmds/ui/models) the `cdktf-cli` uses the Terraform CLI and the Terraform Cloud API to provision infrastructure.  
It would be useful to extract this code into a separate package as this would allow us to use `JSII` to offer that package across the languages we support.  
This would satisfy the [requests for such an api](https://github.com/hashicorp/terraform-cdk/issues/237) and could serve as a foundation e.g. when building integrations into testing frameworks.  
Besides that, it would also serve as a precursor to refactoring the `cdktf-cli` "UI" which makes sense to do before working on e.g. [supporting displaying individual attributes](https://github.com/hashicorp/terraform-cdk/issues/114) for a `diff`.

#### Tasks
- [ ] Extract code from [models directory](https://github.com/hashicorp/terraform-cdk/tree/main/packages/cdktf-cli/bin/cmds/ui/models) into a separate package
- [ ] Add / Move tests for that package
- [ ] Configure JSII to build and publish this package in other languages
- [ ] Add Readme to package (optional: with first rough description that could serve as docs)
- [ ] Research & write follow-up issue for adding CDKTF specific apis to that package (might be done as part of a later "UI" refactoring): E.g. for triggering a synth, listing stacks, etc. (later to be used by the `cdktf-cli` when it is refactored.
- [ ] _…probably more…_

### References

- https://github.com/hashicorp/terraform-cdk/issues/237
- https://github.com/hashicorp/terraform-cdk/issues/114
- https://github.com/hashicorp/terraform-cdk/issues/152
